apiVersion: v1
kind: Pod
metadata:
  name: kuard
  labels:
    name: kuard
spec:
  containers:
  - name: kuard
    image: gcr.io/kuar-demo/kuard-amd64:1
    env:
      - name: DEMO
        value: "test123"
      - name: TEST
        value: "Moto jest super!"
