apiVersion: v1
kind: ConfigMap
metadata:
  name: kuard-config
data:
  APP1: "Demo!"
  SVC_XYZ: "moto.host.xyz"
---
apiVersion: v1
kind: Pod
metadata:
  name: kuard
  labels:
    name: kuard
spec:
  containers:
  - name: kuard
    image: gcr.io/kuar-demo/kuard-amd64:1
    env:
      - name: DEMO
        value: "test123"
      - name: TEST
        value: "Moto jest super!"
      - name: APP1
        valueFrom:
          configMapKeyRef:
            name: kuard-config
            key: APP1
      - name: SVC
        valueFrom:
          configMapKeyRef:
            name: kuard-config
            key: SVC_XYZ
