apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-azurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: my-azurefile
      containers:
      - name: empty-pod-bb
        image: busybox
        command: ['sh', '-c', 'echo running! && sleep 3600']
        volumeMounts:
        - name: volume
          mountPath: /volume/
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: empty-pod-pkad
        image: poznajkubernetes/pkad
        volumeMounts:
        - name: volume
          mountPath: /volume/
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8080