apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.front.name }}
  labels:
    {{- include "azure-vote.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.front.name }}
  ports:
  - port: {{ .Values.front.port }}
    targetPort: http