apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.back.name }}
  labels:
    {{- include "azure-vote.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.back.name }}
  ports:
  - port: 6379
    targetPort: redis